3 show a summary of the attack graph for a consequence in the web UI
Spyderisk/system-modeller pull request #18
Opened 2023-04-25 13:59 UTC by panositi

2023-04-26 13:37 UTC, kenmeacham requested changes
I've checked out the branch and tested SSM. All seems generally fine with the new functionality. I confirmed that you can get a different attack path on different consequences and that the results are cached. Also, results are cleared when running risk calc, so that's good. No major issues that I can see.

For the code itself, I've been through the code changes and made comments on various files. Nothing major - generally a bt of tidying up, removing commented out code, fixing copyright headers, etc.

I have not looked at the attack path algorithm code in great detail, but quick scan looks OK.

2023-04-28 09:45 UTC, panositi commented on src/main/java/uk/ac/soton/itinnovation/security/systemmodeller/rest/ModelController.java
> +import java.util.Arrays;
done
I will not remove the Dataset import as it's referenced in another block of code that is currently commented out.

2023-04-28 09:49 UTC, panositi commented on src/main/webapp/app/modeller/actions/ModellerActions.js
> +export function getShortestPathThreats(modelId, msUri) {
moved at the end of the file

2023-04-28 09:56 UTC, panositi commented on src/test/java/uk/ac/soton/itinnovation/security/modelvalidator/test/AttackPathTester.java
> +            //targetUris.add("system#MS-LossOfConfidentiality-a40e98cc");
The MS uri in that line is valid in case we need to test a list of target MS, so we'd better keep that line.

2023-05-31 09:44 UTC, panositi commented on src/main/webapp/app/modeller/actions/ModellerActions.js
> +        //let uri = encodeURIComponent('/models/' + modelId + "/shortestpath?longPath=true&normalOperations=false&targetURIs=system#" + shortUri);
deleted

2023-05-31 09:44 UTC, panositi commented on src/main/webapp/app/modeller/actions/ModellerActions.js
> +                //payload: response.data['graphs']["system#"+shortUri]['threats']
commend deleted

2023-05-31 09:47 UTC, panositi commented on src/main/webapp/app/modeller/components/panes/details/accordion/panels/ThreatsPanel.js
> -                col: (props.name === "direct-effects") ? "likelihood" : "risk",
I cannot see that, so I cannot change it

2023-05-31 09:50 UTC, panositi commented on src/main/webapp/app/modeller/reducers/modeller.js
> +        loadingAttackPath: false,
code changed no need for ladingAttackPath attribute there

2023-05-31 09:52 UTC, panositi commented on src/main/webapp/app/modeller/reducers/modeller.js
> +            attackPaths: {},
attackPaths attribute is not used anymore removed

2023-05-31 09:54 UTC, panositi commented on src/main/webapp/app/modeller/reducers/modeller.js
> +                calculatingRisks: true,
comma removed

2023-05-31 09:54 UTC, panositi commented on src/main/webapp/app/modeller/reducers/modeller.js
> +            attackPaths: {},
attackPaths removed

2023-05-31 10:11 UTC, panositi commented on src/test/java/uk/ac/soton/itinnovation/security/modelvalidator/test/AttackPathTester.java
> +/////////////////////////////////////////////////////////////////////////
copyright statement updated

2023-05-31 10:12 UTC, panositi commented on src/test/java/uk/ac/soton/itinnovation/security/modelvalidator/test/AttackPathTester.java
> +        /*
removed commented out code

2023-05-31 10:59 UTC, scp93ch commented on src/main/webapp/app/modeller/components/panes/details/accordion/panels/ThreatsPanel.js
> -                col: (props.name === "direct-effects") ? "likelihood" : "risk",
Well @kenmeacham is right - the indentation on lines 44-47 is done with a weird invisible character. It needs fixing.

2023-05-31 11:09 UTC, scp93ch requested changes
SonarLint highlights many cases of defined but unused variables and methods which should be removed.
There are unused imports which should be removed (e.g. in LogicalExpression.java).
There is also quite a lot of unnecessary commented out code so please see what could be deleted there.
It would be nice to have more consistent formatting in the new code at least (so for example many cases of "for(" rather than "for (" (the later is to be used surely). Perhaps you can run the new files through a basic code formatter?

2023-06-22 11:45 UTC, panositi commented
The exposed API for shortest path takes two parameters:
- allPaths
- normalOperations

The UI button for  "Calculate Attack Path" invokes the shortest path calculation with allPaths=TRUE and normalOperations=FALSE.

Internally the AttackTree object is initialised with `futureRisk`=FALSE mode. This parameter should be either exposed to the API and a button consequently, or detect automatically the last valid risk calculation mode.

As a temporary fix futureRisk will be fixed to `FUTURE` mode.

2023-06-26 14:50 UTC, scp93ch commented
1. I think the API endpoint for this is "shortestpaths" which is odd given that there is a parameter to determine whether to return all paths or just the shortest. Can we rename it to be "threatgraph"?
1. It needs to have the 2 existing parameters plus one for the risk calculation mode.
1. When I looked at the code, it seemed that the call from the client was for "allPaths", why? Should be just the shortest I think.
1. The call from the client should explicitly specify the risk calculation mode, but this complexity should not be exposed to the user. Therefore the client needs to know what mode was used in the last risk calculation. This should be returned in the risk calculation response but may not be currently stored in the client's state.

There are then issues around the previous risk calculation not being saved:

5. we should make sure that the service drops the previous saved risk calculation results when an unsaved risk calculation is done
5. when the service receives a request to get the attack graph it should check whether the requested risk calculation mode matches the last saved risk calculation, use it if so, or recalculate the risks and not save it if not (the second situation would not occur in the web client given the tweaks above)
5. we should switch the default risk calculation mode to the "saved" version so that if the user uses the attack graph buttons then the information is readily available on the service

2023-06-26 16:47 UTC, panositi commented
@scp93ch I think points 1-3 can be easily implemented, although it might not be necessary to pass the risk calculation mode as a parameter.

The `attack graph` call operates inside the system modeller and is using JenaQuerierDB to get the information that needed for the attack graph calculation. If there is a way to extract the risk calculation mode from the querierDB the issue is easily solved, for example the extracted values could be a) no-risk-calculation, b)  future, and c) current.

The algorithm will use that risk calculation mode info automatically to complete its attack path calculations or reject the attack path calculation when there is no valid risk calculation done. 

The actual question then is the `saved` vs `unsaved` risk calculation, and in particular if data retrieved from querierDB are valid when the last risk calculation mode was run as `unsaved`.

In addition, such last risk calculation mode parameter can be returned to risk calculation results as well as the model results and should be used by the UI to provide a visual display of the last valid risk calculation.

2023-06-27 09:31 UTC, kenmeacham commented
> @scp93ch I think points 1-3 can be easily implemented, although it might not be necessary to pass the risk calculation mode as a parameter.

I agree.

> The `attack graph` call operates inside the system modeller and is using JenaQuerierDB to get the information that needed for the attack graph calculation. If there is a way to extract the risk calculation mode from the querierDB the issue is easily solved, for example the extracted values could be a) no-risk-calculation, b) future, and c) current.

I can confirm that there is a  `core#riskCalculationMode` triple saved in the system model, which is either "FUTURE" or "CURRENT". We ought to be able to load in this value where you load in you data for the attack path

> The algorithm will use that risk calculation mode info automatically to complete its attack path calculations or reject the attack path calculation when there is no valid risk calculation done.

Seems OK.

> The actual question then is the `saved` vs `unsaved` risk calculation, and in particular if data retrieved from querierDB are valid when the last risk calculation mode was run as `unsaved`.

Personally I doubt this, but @mike1813 may be able to comment.

> In addition, such last risk calculation mode parameter can be returned to risk calculation results as well as the model results and should be used by the UI to provide a visual display of the last valid risk calculation.

If we can get hold of the `core#riskCalculationMode` (see above), we should be able to add the value to the returned data from a risk calc. We also need to add the value to a returned system model for the GUI. I can also confirm that there is a method to get this value, but it has not yet been hooked into the ModelDTO being returned. We should create separate issues for these, as they are probably not directly required for this current issue.

2023-06-27 10:04 UTC, mike1813 commented
I believe we need to make the following changes:

- [ ] The U/I client buttons for starting a risk calculation should by default use the option to save the results.
- [ ] The RiskCalculator should clear the results of any previous risk calculation from the triple store before loading the model.
- [ ] The U/I client should store and display the `core#riskCalculationMode` value ('CURRENT' or 'FUTURE') from the risk calculation response message.
- [ ] When the user presses the button to get a threat graph for a selected misbehaviour, the U/I client should use the saved value for `core#riskCalculationMode` as an argument. That way it is asking for a threat graph corresponding to the displayed likelihood levels, by using the same risk calculation mode that led to those displayed likelihoods.
- [ ] When the service receives the request for a threat graph calculation, it should check if there is a saved risk calculation, and if so, whether it has the requested risk calculation mode. It should run the risk calculation if saved results are absent or the wrong type.

The first three of these changes are really addressing other issues. The option to not save risk calculation results was introduced to support iterative recalculation in an automated search to find control strategies where speed is of the essence. It wasn't meant as a U/I option. Clearing previous risk calculation output from the triple store ensures consistency with the latest client request, which is a better starting position for any 'post processing' calculation, not just the threat path extraction. And since the results from a risk calculation depend on which mode was selected, the U/I really shouldn't display risk calculation results without it, because the user as well as the U/I itself need to know which mode was used to get those results.

I can create separate issues for those three. The first and third are U/I issues so I propose @kenmeacham should cover those. I can handle the second issue as I worked on the risk calculator code over the last year.

The last two issues are specific to the threat graph display. I assume @kenmeacham and @panositi already have those covered.

2023-06-28 09:45 UTC, scp93ch commented
Following further team discussions, the following strategy was agreed:

- [ ] The U/I client should store and (ideally) display the core#riskCalculationMode value ('CURRENT' or 'FUTURE') from the risk calculation response message.
- [ ] When the user presses the button to get a threat graph for a selected misbehaviour, the U/I client should use the saved value for core#riskCalculationMode as an argument. That way it is asking for a threat graph corresponding to the displayed likelihood levels, by using the same risk calculation mode that led to those displayed likelihoods.
- [ ] When the service receives the request for a threat graph calculation, it should check if there is a saved risk calculation, and if so, whether it has the requested risk calculation mode. If not, it should return an error (possible a 400) along with a textual message explaining that a saved risk calculation is a prerequisite.
- [ ] The attack graph endpoint should be renamed to "threatgraph".
- [ ] The web client should request the shortest paths, not all paths.

To avoid the situation where the web UI gets a threat graph calculation error:

- [ ] The U/I client buttons for starting a risk calculation should by default use the option to save the results.
- [ ] The attack graph button should be disabled if there is no saved risk calculation (i.e. if the risk calculation button is not green). Ideally, the disabled button would have a tooltip explaining that a saved risk calculation was required.

It is not necessary to change the RiskCalculator behaviour: we do not need to clear the results of any previous risk calculation from the triple store before loading the model for a new calculation.

2023-06-28 10:46 UTC, mike1813 commented
I suggest we also store (though not display) the timestamp for the last saved risk calculation in the U/I, and include this as an argument. That way if there is a saved risk calculation at the service, system-modeller can check if it is the same one the client is using.

This could be done instead of checking the risk calculation mode. If the timestamp doesn't match, then we return the error, as described by Stephen. If the timestamp does match, then the risk calculation mode should also match.

The advantage this brings is that it detects the case where a different client runs a saved risk calculation after the one that requested the attack graph analysis. If this other client changed risk calculation inputs (e.g., control selection or coverage, or assumed TW levels), then the attack graph wouldn't be correct for the displayed likelihood data.

The timestamp we would need is a property of the system model graph (`http://purl.org/dc/terms/modified`). It is added in the risk calculator. This is already included in the ModelDB class as variable 'modified', but it is not set until the very end of the risk calc, after the results have been returned to the client. That should be an easy fix, though.

This extension could be done separately, if desired. It should be a minor change on what @scp93ch proposed above.

2023-06-28 11:18 UTC, mike1813 commented
Just checked - it seems (based on code comments) that http://purl.org/dc/terms/modified is not deserialized correctly by the ModelDB class. I still think the timestamp should be used, but it should be added in a separate update, after any issues within ModelDB have been checked and fixed.

2023-07-05 14:48 UTC, kenmeacham approved these changes

2023-07-05 16:11 UTC, merged