26 review and improve docker compose scripts
Spyderisk/system-modeller pull request #53
Opened 2023-07-03 13:24 UTC by panositi

2023-07-04 14:04 UTC, scp93ch requested changes
The `provisioning/ssm.entrypoint.sh` file should not be there.

2023-07-04 14:28 UTC, panositi commented on src/main/resources/application.properties
> +reset.on.start=${RESET_ON_START:true}
removed `provisioning/ssm` and revoke application.properties change

2023-07-05 11:52 UTC, scp93ch commented
I've made a commit to `README.md` and `docker-compose.yml` (please check it).

Aside from that:

The `provisioning/keycloak/healthcheck.sh` script has been added but it is not referenced in any of the docker files. Presumably we need to add in a `healthcheck` statement to `docker-compose.yml`?

`docker-compose.test.yml` refers to `.env.template` as does the `test.yml` CI script. If we needed this I think just one place would do. However, the whole `.env.template` file is commented out so surely the references to `.env.template` are not required?

2023-07-05 13:32 UTC, scp93ch approved these changes

2023-07-05 13:35 UTC, merged